version: '3.9'
services:  
  traefik:
    restart: unless-stopped
    # The official v2 Traefik docker image
    image: traefik:v2.9.6
    # Enables the web UI and tells Traefik to listen to docker
    command:
#      - "--accesslog=true"
#      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
 #     - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.websecure.forwardedHeaders.insecure"
      - "--certificatesresolvers.le.acme.email=team@tovera.com"
      - "--certificatesresolvers.le.acme.storage=./acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
#      - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      # The HTTP port
#      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "127.0.0.1:8080:8080"
      # Local dev instance
      #- "8000:80"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - "./acme.json:/acme.json"

  # Need to add port range for iortc so we don't have to use network=host
  # https://github.com/aiortc/aioice/pull/63
  worker0:
    restart: unless-stopped
    image: air-infer-api:latest
    command: uvicorn main:app --host 0.0.0.0 --port 8000
#    ports:
#      - "127.0.0.1:8000:8000"
    shm_size: 1gb
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
      WEB_CONCURRENCY: 32
      #CUDA_VISIBLE_DEVICES: 0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.asr.rule=Host(`asr.air.tovera.io`)"
      - "traefik.http.services.asr.loadbalancer.server.port=8000"
      - "traefik.http.routers.asr.tls=true"
      - "traefik.http.routers.asr.tls.certresolver=le"
#      - "traefik.http.middlewares.asr-strip.stripprefix.prefixes=/asr"
#      - "traefik.http.middlewares.asr-strip.stripprefix.forceslash=true"
#      - "traefik.http.routers.asr.middlewares=asr-strip"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
